# Generated by Django 2.1 on 2018-09-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Algorithms',
            new_name='Algorithm',
        ),
    ]
