# Generated by Django 2.1.1 on 2018-09-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_algorithm_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='blogAuthor',
            field=models.CharField(default=1209.2018, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='pic_name',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
