# Generated by Django 2.1.1 on 2018-09-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0005_remove_algorithm_blogauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='Author',
            field=models.CharField(default=11.11, max_length=200),
            preserve_default=False,
        ),
    ]
