# Generated by Django 2.1.1 on 2018-09-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0006_algorithm_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='Author',
            new_name='author',
        ),
    ]
