# Generated by Django 2.1.1 on 2018-09-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0007_auto_20180912_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='author',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='pic_name',
        ),
    ]
