# Generated by Django 2.1.1 on 2018-09-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0008_auto_20180913_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='author',
            field=models.CharField(default=11.11, max_length=200),
            preserve_default=False,
        ),
    ]
